language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
    include:
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - composer self-update
    - composer --version
    - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php bin/coveralls -v
